// Central icon map: friendly names → @vicons/ionicons5 components.
// Render inside an <n-button> #icon slot (auto-sized) or wrap with <n-icon :size>.
export {
  PulseOutline as IconActivity,
  ReorderFourOutline as IconAlignLeft,
  CheckmarkOutline as IconCheck,
  CheckmarkCircleOutline as IconCheckLg,
  ChevronDownOutline as IconChevron,
  TimeOutline as IconClock,
  CopyOutline as IconClone,
  CloseOutline as IconClose,
  GitCompareOutline as IconConflicts,
  ServerOutline as IconDatabase,
  DownloadOutline as IconDownload,
  LayersOutline as IconDuplicates,
  CreateOutline as IconEdit,
  ExpandOutline as IconExpand,
  ContractOutline as IconContract,
  SyncOutline as IconFetchRefresh,
  FolderOutline as IconFolder,
  InformationCircleOutline as IconInfo,
  LockClosedOutline as IconLock,
  LogOutOutline as IconLogout,
  MoonOutline as IconMoon,
  AddOutline as IconPlus,
  RefreshOutline as IconRefresh,
  SearchOutline as IconSearch,
  SettingsOutline as IconSettings,
  SunnyOutline as IconSun,
  SyncOutline as IconSync,
  PricetagOutline as IconTag,
  TerminalOutline as IconTerminal,
  TrashOutline as IconTrash,
  CloudUploadOutline as IconUpload,
  WarningOutline as IconWarn,
} from '@vicons/ionicons5'
